version: '2'
services:
  host-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /init.sql
    volumes:
        - ./init.sql:/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - "labb-network"
  backend:
    depends_on:
      - host-db
    image: backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: "mvn spring-boot:run"
    networks:
      - "labb-network"
networks:
  labb-network:
    driver: bridge